import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import Providers from "./lib/Providers";
import Navigation from "./components/header/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	const messages = useMessages();
	return (
		<html lang={locale}>
			<body className={inter.className}>
				<Providers>
					<NextIntlClientProvider locale={locale} messages={messages}>
						<Navigation />
						{children}
					</NextIntlClientProvider>
				</Providers>
			</body>
		</html>
	);
}
